### ISSUE TITLE
Lint for standardized Ellipses

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#269]
This urgently applies to LBF, but will be used in PP as soon as LBF is finished. I believe that @hsteck1844 decided against using the unicode ellipses character in MB and favored 3 dots. There are outlier cases where the ellipsis follows a '... closing quotation mark etc. I think I have been spacing ` ... ` around three periods, but again, we need to standardize.

**Comment by mattleff** [comment]
@hsteck1844 @kenton-r Is it still better today to use triple dots `...` vs the Unicode ellipsis character `…`?

**Comment by kenton-r** [comment]
So with English it is preferred to use the ellipsis character because it maintains the consistent punctuation spacing.
However we are dealing with Thai that is different. I would recommend two options: 

1. No spaces around the ellipsis character unless there needs to be a comma (sentence) like break after the ellipsis.
2. Use a space before and after together with the three dots with spaces between.

The first option seems to be more Thai because having things spaced out is not like their sentence structure which has no spaces.

**Comment by hsteck1844** [comment]
Personally, I strongly prefer the ellipses to appear like there is a space between the dots. And because the spaces in the Unicode character are noticeably narrower than normal spaces, it looks messy to me. So I agree that choosing one of Kenton's two options seems best. 

One question to consider might be, are the ellipses most/always used _within_ a sentence? Or do the ellipses sometimes/frequently indicate an omission that goes beyond the bounds of a single sentence? If it's the latter, then it seems we would want spaces before and after. And perhaps in the case of ellipses, should those spaces be used in _all_ cases (so as not to appear inconsistent)?

I'm okay with choosing the Unicode character, however, if y'all vote that way. Whatever we do should be consistent, if course. Should be easy to find any ellipses and make sure they are uniform.

**Comment by hsteck1844** [comment]
@bountonw , did you ever share what appeals to you about using the Unicode ellipses? 

Perhaps I should mention, if three dots are used, then we need to make sure _non-breaking spaces_ are used between the three dots.

**Comment by kenton-r** [comment]
I have used dots with half-spaces in English books. I feel that full spaces between dots produce the appearance that is too big.
So another option is half-spaces between and full spaces before and after.

I will post some examples.

**Comment by kenton-r** [comment]
[ellipsis-examples.pdf](https://github.com/bountonw/translate/files/15173038/ellipsis-examples.pdf)
This is an example of the three variations.

**Comment by bountonw** [comment]
Dots and half spaces look best. 

I like the concept of using the Unicode,because it is one character, but I don't like how it looks.

**Comment by hsteck1844** [comment]
I agree with you, Brian.

**Comment by kenton-r** [comment]
the text for the three dots and half-spaces:
. . .

**Comment by bountonw** [comment]
To clarify. I vote for dots separated by half spaces surrounded by spaces. But I am happy to go with whatever the consensus is.

**Comment by mattleff** [comment]
@bountonw One idea is we could use (and lint) for the Unicode character in the Markdown files, but replace it with the three dots and half-spaces in a Lua filter in the export process. Would that be cleaner for other use-cases where we actually want a real ellipsis?

**Comment by bountonw** [comment]
Think `md > txt` `md > md` `md > pdf` `md > html`.

Will we want the Unicode symbol in any of these? It looks ugly to me.

Points to consider:

* Linting complexity 
* Display in other formats
* Best source code for conversion to the various formats.

If txt is full spaces, maybe we should code to that and convert to half spaces for LaTeX and InDesign and `<span break="no">` or whatever the html or css would be for html.

`พระเจ้าทรงรักโลก . . . เพื่อทุกคน`

**Comment by mattleff** [comment]
@bountonw I would focus on what's easiest for you to write in the translation process, and yet unambiguously represent the semantics of an ellipsis. We can convert any text to our triple-dots-half-spaces-forbidden-break string for all outputs. But if ever use that text for anything else we add ambiguity. Would we ever use ` . . . . . `, etc. for a stylistic element in markdown source? If so, that's going to make it harder to lint and know when to replace with half-spaces. I would vote for Unicode ellipsis in the markdown files, and converting that to our special string for all outputs.

**Comment by bountonw** [comment]
Ok. That will require a hefty PR. Can we separate by book at the moment and do LBF first? Going through all of the ellipses in PP and MB sounds like too much to tackle.
