### ISSUE TITLE
Figure out missing book name

### ISSUE THREAD

**Issue by bountonw** [bountonw/translate#96]
Part of PR #89

**Comment by bountonw** [comment]
@mattleff What is this?

**Comment by mattleff** [comment]
<img width="745" alt="Untitled" src="https://github.com/bountonw/translate/assets/120155/ab389d9d-1ed4-4340-be32-3cb04b3e33dd">

@bountonw The book title is missing in the generated PDFs.

**Comment by bountonw** [comment]
The generated pdf should have `[bookcode][## chapter number]_[stage]_[timestamp YYYYMMDD_HHMMSS]: Title` In this case it would be `PP02_public_timestamp: The Creation`.

**Comment by bountonw** [comment]
@tonyquicktech Can you do this?

**Comment by mattleff** [comment]
@bountonw In working on this bug I ran into a question: Do we want to keep the book/author/translator info in the individual markdown files, like this:

https://github.com/bountonw/translate/blob/7582834dba4a1c615a2369f6547a7a2371902c43/th/PP/PP5/03_public/PP59_th.md?plain=1#L1-L19

versus in the `metadata.yaml` shared by all the chapters in that volume:

https://github.com/bountonw/translate/blob/7582834dba4a1c615a2369f6547a7a2371902c43/th/PP/PP5/metadata.yaml#L1-L14

Obviously we need to correct the data in the `metadata.yaml` files, but are you good removing the book/author/translator yaml metadata from the individual chapter files and adding it into the `metadata.yaml`s instead? It is more "correct" to have a single place to edit that information (like normalization in databases), but there can be good reasons for "denormalizing" data too. That's why I'm wanting to check before I move it all into the `metadata.yaml`s.

**Comment by bountonw** [comment]
Book and author definitely. For PP and MB yes on translator. It is possible in the future that some books might have more than one translator, but that is way down the road.
